[package]
name = "jep106json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jep106 = "0.2.6"
serde_json = { version = "1.0.82", features = ["preserve_order"] }
